### ISSUE TITLE
The link to the IDP provider config is broken in README

### ISSUE THREAD

**Issue by alejdg** [canonical/iam-bundle-integration#26]
In the README, the link https://github.com/canonical/kratos-external-idp-integrator/blob/main/config.yaml is broken in: 
> More information about the Idp provider configuration can be found [here](https://github.com/canonical/kratos-external-idp-integrator/blob/main/config.yaml)

**Comment by nsklikas** [comment]
Sorry about that, we recently migrated to using charmcraft.yaml for our metadata/config/actions and we didn't update the docs. You can find see the charm's config [here](https://github.com/canonical/kratos-external-idp-integrator/blob/main/charmcraft.yaml#L20). We will update docs soon.

Thanks for reporting this.
